# Generated by Django 4.0.10 on 2023-03-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default='post title', max_length=255),
        ),
    ]
