# Generated by Django 4.0.10 on 2023-03-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='Type of Card', max_length=255),
        ),
    ]
