# Generated by Django 4.0.10 on 2023-03-12 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_carousel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
