# Generated by Django 4.0.10 on 2023-03-12 22:47

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_delete_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='attachment',
        ),
        migrations.AddField(
            model_name='carousel',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='yourmom', force_format=None, keep_meta=True, quality=-1, scale=None, size=[500, 500], upload_to='card_images'),
            preserve_default=False,
        ),
    ]
