# Generated by Django 4.0.10 on 2023-03-14 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_alter_carousel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='image',
            new_name='image1',
        ),
    ]
