# Generated by Django 4.0.10 on 2023-03-14 02:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_rename_image_carousel_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='card_images'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='card_images'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='card_images'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='image5',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='card_images'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='card_images'),
        ),
    ]
