# Generated by Django 4.0.10 on 2023-03-15 02:43

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_carousel_image2_carousel_image3_carousel_image4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='carousel',
            name='image5',
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[500, 500], upload_to='photos')),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('imageSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='card.imageset')),
            ],
        ),
        migrations.AddField(
            model_name='carousel',
            name='imageSet',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='card.imageset'),
        ),
    ]
